name: Hello Devops
on: 
 workflow_dispatch: 
   

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Say Hello Devops!!"
     
 
