name: Hello Devops
on: 
 push:
   branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        user: actions/checkout@v4
      - name: Say Hello
        run: echo "Say Hello Devops!!"
     
 
