---
name: Environment Variables
on:
  workflow_dispatch: 
env:
  APP_NAME: myapp
jobs:
  env-variables:
    env:
      ENVIRONMENT: staging
    runs-on: ubuntu-latest
    steps:
        - name: Print the variables
          env:
            VERSION: 1.0.0
          run: |
            echo "Wokrflow env variableS $APP_NAME"
            echo "JOB level env $ENVIRONMENT"
            echo "Step level env variable $VERSION"

